spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1/security_jwt?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    #监控统计拦截的filters
    filters: stat,wall,log4j
    #druid配置
    #配置初始化大小/最小/最大
    initialSize: 5
    minIdle: 5
    maxActive: 20
    #获取连接等待超时时间
    maxWait: 60000
    #间隔多久进行一次检测，检测需要关闭的空闲连接
    timeBetweenEvictionRunsMillis: 60000
    #一个连接在池中最小生存的时间
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
    poolPreparedStatements: false
    maxPoolPreparedStatementPerConnectionSize: 20
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties:
      druid:
        stat:
          mergeSql: true
          slowSqlMillis: 5000

#配置项目统一编码
http:
  encoding:
    charset: utf-8
    force: true
    enabled: true

#redis配置
  application:
    name: spring-boot-redis
  redis:
    host: 127.0.0.1
    port: 6379
    password: myredis
    database: 0
    timeout: 20000
#    cluster:
#      nodes: 192.168.211.134:7000,192.168.211.134:7001,192.168.211.134:7002
#      maxRedirects: 6
    pool:
      max-active: 8
      min-idle: 0
      max-idle: 8
      max-wait: -1

#mybatis是独立节点，需要单独配置
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.jwt.cephce.demo.entity
  configuration:
    map-underscore-to-camel-case: true

#项目访问地址
server:
  servlet:
    context-path: /JwtDemo
  tomcat:
    uri-encoding: UTF-8
  port: 8080

#自定义参数，可以迁移走
token:
  #token失效时间（不是refreshToken）(这是自定义的)(秒)
  expirationSeconds: 3000
  #默认7天登录有效(根据业务更改)
  validTime: 7


